### ISSUE TITLE
[object Object],[object Object],[object Object],ModuleParseError: Module parse failed: Unterminated string constant (6:0) You may need an appropriate loader to handle this file type

### ISSUE THREAD

**Issue by mrudula1412** [SAP-samples/cloud-mdk-tutorial-samples#2]
Hi ,

We are facing below error while deploying project created referring below link.

Create a Slider Custom Control in an MDK App (Using Metadata Approach)

Error-

ERROR in ./build.definitions/MDK_Slider/Extensions/MySliderModule/controls/MySliderPlugin/android/MySlider.ts 6:0
Module parse failed: Unterminated string constant (6:0)
You may need an appropriate loader to handle this file type.
| var _1 = require("");
| tns - core - modules / ui / core / view;
> ';;
| var platform_1 = require("tns-core-modules/platform");
| function GetMySliderClass() {
 @ ./build.definitions/application-index.js 6:87-180
[object Object],[object Object],[object Object],ModuleParseError: Module parse failed: Unterminated string constant (6:0)
You may need an appropriate loader to handle this file type.
| var _1 = require("");
| tns - core - modules / ui / core / view;
> ';;
| var platform_1 = require("tns-core-modules/platform");
| function GetMySliderClass() {
undefined
Command failed: node "/tmp/vscode-unpacked/vscode_npm_@ext-mdkvsc-npm-rel_mdkvsc-wing@1.2.24/extension/tools/application-bundler/bundler-cli.js" --nativescript-project "/home/user/tmp/MDKBundleTarget/MDK_Slider/app" --seam-project "/home/user/tmp/MDKBundleFactory/MDK_Slider/MDK_Slider" --externals file-system ui/dialogs fs-extra dateformat nativescript-toasty --filters  --devtool source-map --create-bundle

Regards,
Mrudula

**Comment by jitendrakansal** [comment]
@mrudula1412 
There is typo in MySliderPlugin/android/MySlider.ts 
instead of import { layout } from **''tns-core-modules/ui/core/view';**
use import { layout } from **'tns-core-modules/ui/core/view';**
(there is an extra single quote). 
Re-deploy the project, it should work. 
I will fix the tutorial.

**Comment by mrudula1412** [comment]
Hi Jitendra,

I made changes in my project code according to your reply and deployed project again.
It's working fine.
Thanks a lot for your quick help.

Regards,
Mrudula
