### ISSUE TITLE
CheckRequiredFields action example

### ISSUE THREAD

**Issue by MiqueiasMaia** [SAP-samples/cloud-mdk-tutorial-samples#8]
@jitendrakansal, do you have any examples with CheckRequiredFields action? I didn't find any documentation, question or issue with this action type. 
I've made an action with this tipe to check my form when I click in a button, but always returns to my failure action, In my form I have list pickers, simple properties and others.
What is the correct way to use it?

**Comment by jitendrakansal** [comment]
@MiqueiasMaia can you share how did you try it out?

**Comment by MiqueiasMaia** [comment]
@jitendrakansal, i've created a form and a check Required Fields action and i've put this action to run onClick submit button. In check required fields actions, i've selected the field names from page that I want to validade.
On success will call the createEntity action, on failure will call the failure message. But it always call the failure message.

**Comment by jitendrakansal** [comment]
@MiqueiasMaia do you have those FormCell controls on a section page (Add FormCell container on a section page and then add FormCell controls in that container)? OR on a FormCell container (FormCell page)?

I noticed that it always call the failure action when calling CheckRequiredFields action in FormCellSection (checking with development on this) but works fine in FormCellContainer.

**Comment by MiqueiasMaia** [comment]
@jitendrakansal, unfortunatelly I need to use a SectionPage to apply some Compounds, because I have a behavior that uses some modals to create another entities and I need to show them (and compounds aren't disponible on FormCell pages). So, my form is on a SectionPage and inside this section page i've divided my form in some Form Cell Sections (actually, 6 sections).

If you find another conclusion about this, I'll be greatfull if you share with us. Maybe if SAP MDK development team improve the application of this action in SectionPages and Form Cell Sections, it could be easy for MDK developers.

If it not works good, I'll create a JS rule to check individually wich field is empty. 

Anyway, thanks @jitendrakansal .

**Comment by jitendrakansal** [comment]
This issue has been fixed and should fine with MDK client 6.0.5 release.

**Comment by MiqueiasMaia** [comment]
Great! Thanks for sharing, @jitendrakansal.
